# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 2128cfc09a395d35c39b3f68be590aac734cbf39b929a2ba3a4abba67a68493508fdd3d5bc0f504f21a74c2d8616b9b6d6c2899280ec41b31d54ad252cb78243

test:
  secret_key_base: 96b92fd05044865dd1a6e6e48ca05fe42e3c8a331f85ca9a5592c635114b2c08fa905a6ea00c4373233f69de9b72d2d70a4f9139b1048d93f922b05642784710

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
